/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_beefclassifier_CameraActivity */

#ifndef _Included_com_example_beefclassifier_CameraActivity
#define _Included_com_example_beefclassifier_CameraActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_beefclassifier_CameraActivity
 * Method:    GrabCut
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_beefclassifier_CameraActivity_GrabCut
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
